name: nezha_drive_ai_v9_4
description: "導航管家 Pro V9.4：AI安全管家 + 導航入口完整修正版"
publish_to: "none"
version: 9.4.0+5

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  sensors_plus: ^6.1.0
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
