name: nezha_drive_ai_v10_1
description: "導航管家 Pro V10.1：哪吒AI副駕 + Waze導航 + 測速提醒"
publish_to: "none"
version: 10.1.0+6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  sensors_plus: ^6.1.0
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
